name: Publish

on:
  push:
    branches: [ "more-fixes" ]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🐘 Run Gradle Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build
          concurrent: true
        env:
          ORG_GRADLE_PROJECT_signingKeyBase64: ${{ secrets.signing_key_base64 }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signing_password }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatype_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatype_password }}

      - name: Package
        run: jpackage --verbose "@jpackage.cfg" "@jpackage-windows.cfg"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: ./launcher/build/distributions/dino-dinner-0.0.1.msi
          name: windows-installer
          retention-days: 1