name: Publish

on:
  push:
    branches: [ "more-fixes" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 🐘 Run Gradle Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishToSonatype closeSonatypeStagingRepository
          concurrent: true
        env:
          ORG_GRADLE_PROJECT_signingKeyBase64: ${{ secrets.signing_key_base64 }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signing_password }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatype_username }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatype_password }}
